// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cp_cor_s
List cp_cor_s(NumericMatrix mat);
RcppExport SEXP _EasyMultiProfiler_cp_cor_s(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(cp_cor_s(mat));
    return rcpp_result_gen;
END_RCPP
}
// cp_cor_t
List cp_cor_t(NumericMatrix mat, NumericMatrix mat2);
RcppExport SEXP _EasyMultiProfiler_cp_cor_t(SEXP matSEXP, SEXP mat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat2(mat2SEXP);
    rcpp_result_gen = Rcpp::wrap(cp_cor_t(mat, mat2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EasyMultiProfiler_cp_cor_s", (DL_FUNC) &_EasyMultiProfiler_cp_cor_s, 1},
    {"_EasyMultiProfiler_cp_cor_t", (DL_FUNC) &_EasyMultiProfiler_cp_cor_t, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_EasyMultiProfiler(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
