# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cp_cor_s <- function(mat) {
    .Call('_EasyMultiProfiler_cp_cor_s', PACKAGE = 'EasyMultiProfiler', mat)
}

cp_cor_t <- function(mat, mat2) {
    .Call('_EasyMultiProfiler_cp_cor_t', PACKAGE = 'EasyMultiProfiler', mat, mat2)
}

